### ISSUE TITLE
CircuitPython_AD569x NOT working on Adafruit Metro ESP32-S3 (Adafruit Product ID: 5500)

### ISSUE THREAD

**Issue by dbiersach** [adafruit/Adafruit_CircuitPython_AD569x#3]
The code example for the Adafruit AD5693R Breakout Board - 16-Bit DAC with I2C Interface [Adafruit Product ID: 5811] provided by Adafruit Learning  (https://learn.adafruit.com/adafruit-ad5693r-16-bit-dac-breakout-board/circuitpython-and-python) fails to run on the Adafruit Metro ESP32-S3 with 16 MB Flash 8 MB PSRAM [Adafruit Product ID: 5500] using CircuitPython 8.2.9.

I connected the DAC and the Metro ESP32-S3 via an Adafruit STEMMA QT / Qwiic JST SH 4-Pin Cable - 200mm Long [Adafruit Product ID: 4401] The green power light on the DAC was on, and Adafruit's I2C Debugging script indicated two I2C addresses found: ['0x36', '0x4c']

The same unmodified example (and cable) runs perfectly on an Adafruit KB2040 with CircuitPython 8.2.9.

Below is the error output in Thonny when running the example on the Metro ESP32-S3:

![DAC Error](https://github.com/adafruit/Adafruit_CircuitPython_AD569x/assets/1501086/927284c1-01c0-4c41-b25a-2f991f96e70c)

I suspect this is a bug in the I2C stack on the Metro ESP32-S3, but this bug is reproducible using this new DAC library, so it might offer a useful place to start tracking down the discrepancy.

**Comment by BlitzCityDIY** [comment]
i was able to reproduce this and also saw the same behavior that it did work with other boards (esp32-s3 tft feather and rp2040 feather). a [PR to update the reset() function](https://github.com/adafruit/Adafruit_CircuitPython_AD569x/pull/5) was just merged in

**Comment by BlitzCityDIY** [comment]
fix is in the newest library release
